### ISSUE TITLE
How to get camera pitch & yaw?

### ISSUE THREAD

**Issue by Hydrowind** [farminf/pannellum-react#17]
just like in pannellum.js you can get the camera pitch & yaw by viewer.getPitch() & viewer.getYaw(). Thanks in advance..

**Comment by farminf** [comment]
Weekend is here... will be there soon :)

**Comment by farminf** [comment]
Try new version (0.2.6) and by getting the ref of the component you can call `getViewer` function and access to all viewer functions. so for example for getting pitch:
`this.yourRef.current.getViewer().getPitch()`

**Comment by Hydrowind** [comment]
thank you @farminf i appreciate it so much!
let me try to use it..

**Comment by Hydrowind** [comment]
by the way where should i put the ref props? i've tried to put it inside Pannellum but that doesn't work.
```
<Pannellum ref={this.viewer} image= "https://pannellum.org/images/alma.jpg">
     <Pannellum.Hotspot />
</Pannellum>
```

i've console log the this.myRef.current but there's no Pannellum.js function there..

**Comment by farminf** [comment]
first of all make sure that you're using last version 0.2.6. then the example of component would be: 
`export default class ImageDemo extends Component {

  constructor(props){
    super(props);
    this.panImage = React.createRef()
  }
    
  
    


    render() {
      return (
        
          <div className="pannellum_div" >
            <Pannellum
              ref={this.panImage}
              width="800px"
              height="400px"
              image={this.state.mediaPhoto}
              pitch={10}
              yaw={180}
              hfov={120}
              autoLoad
              author=""
              title=""
              orientationOnByDefault={false}
              draggable
              keyboardZoom
              mouseZoom
              preview=""      
              previewAuthor=""
              previewTitle=""
              showControls
              showFullscreenCtrl
              showZoomCtrl
              onLoad={()=>{console.log("panorama loaded");}}
              onScenechange={(id)=>{console.log("Scene has change on " + id);}}
              onScenechangefadedone={()=>{console.log("panorama loaded");}}
              onError={(err)=>{console.log("Error" , err);}}
              onErrorcleared={()=>{console.log("Error Cleared");}}
              onMousedown={(evt)=>{console.log("Mouse Down" , evt);}}
              onMouseup={(evt)=>{console.log("Mouse Up", evt);}}
              onTouchstart={(evt)=>{console.log("Touch Start", evt);}}
              onTouchend={(evt)=>{console.log("Touch End", evt);}}
              hotspotDebug={false}
            >
            </Pannellum>
            <button onClick={()=> console.log(this.panImage.current.getViewer().getPitch())}>get pitch</button>
           
        </div>
      );
    }
}`

**Comment by hwolf0610** [comment]
thank you @farminf 
your commit code work as well.
