### ISSUE TITLE
webpack error occurs on css files

### ISSUE THREAD

**Issue by MarinaUI** [farminf/pannellum-react#28]
I have configured my webpack config. And after adding pannellium-react I get the error:
`ERROR in ./node_modules/pannellum-react/es/pannellum/css/pannellum.css (./node_modules/css-loader??ref--5-1!./node_modules/pannellum-react/es/pannellum/css/pannellum.css)
Module not found: Error: Can't resolve 'img/sprites.svg' in '/node_modules/pannellum-react/es/pannellum/css'
 @ ./node_modules/pannellum-react/es/pannellum/css/pannellum.css (./node_modules/css-loader??ref--5-1!./node_modules/pannellum-react/es/pannellum/css/pannellum.css) 7:1130-1156
 @ ./node_modules/pannellum-react/es/pannellum/css/pannellum.css
 @ ./node_modules/pannellum-react/es/elements/Pannellum.js
 @ ./node_modules/pannellum-react/es/index.js
`
Is something wrong with my config file here is a part of code:
`  rules: [
            {
                test: /\.(js)$/,
                exclude: /node_modules/,
                use: ['babel-loader']
            },
            {
                test: /\.css$/,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            camelCase: true,
                            sourceMap: true
                        }
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    "style-loader", // creates style nodes from JS strings
                    "css-loader", // translates CSS into CommonJS
                    "sass-loader" // compiles Sass to CSS, using Node Sass by default
                ]
            },`

**Comment by farminf** [comment]
Do you have svg file loader config in loaders? 
example like:

`
    {
      test: /\.(gif|png|jpe?g|svg)$/i,
      loaders: ['file-loader?hash=sha512&digest=hex&name=[hash].[ext]','image-webpack-loader']
    },
`

**Comment by MrSandManSy** [comment]
problem：![image](https://user-images.githubusercontent.com/28557698/48239963-eefaff00-e40b-11e8-85b8-f08fa9788d9a.png)
reason：when I ues "npm install pannellum-react" to my project and "npm start", the problems appear.
this is my webpack config：
    module: {
        loaders: [
            {
                test: /\.css$/,
                loaders: ['style', 'css?modules&camelCase'],
                include: PATHS.app
            },
            {    
                test: /\.json$/,
                loader: 'json-loader'      
            },
            {
                test: /\.jsx?$/,
                loader: 'babel',
                include: PATHS.app
            }
            // ,
            // { 
            //     test: /\.(gif|png|jpe?g|svg)$/i, 
            //     loaders: ['file-loader?hash=sha512&digest=hex&name=[hash].[ext]','image-webpack-loader'] 
            // }
        ]
    }

**Comment by farminf** [comment]
Sorry for late reply...
so I've configure webpack (4) from zero (usually i use create-react-app so I don't go into webpack details) and I'm able to run the component without any issue:

webpack config file:
```
const HtmlWebPackPlugin = require("html-webpack-plugin");
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader"
          }
        ]
      },
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        use: [
          'file-loader',
          {
            loader: 'image-webpack-loader',
            options: {
              bypassOnDebug: true, // webpack@1.x
              disable: true, // webpack@2.x and newer
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html"
    })
  ]
};

```

and my dependencies in package.json:
```
"devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "css-loader": "^1.0.1",
    "file-loader": "^2.0.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^4.5.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "style-loader": "^0.23.1",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "dependencies": {
    "pannellum-react": "^1.0.1"
  }

```

and my .babelrc file:
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}


```

**Comment by MrSandManSy** [comment]
@farminf  Ah thanks for reply.next problems,I use it as component in container, when i setState int container, react-pannellum will get render.The next are code.
![image](https://user-images.githubusercontent.com/28557698/48681158-b01f3300-ebdb-11e8-89ba-f710958ff934.png)

**Comment by farminf** [comment]
@MrSandManSy I didn't understand well the issue. Is that when you change the state in the component the image gets re-render? can you screenshot the whole component code?

**Comment by MrSandManSy** [comment]
@farminf Not image,the whole browser gets refresh.It seems like re-render.
![image](https://user-images.githubusercontent.com/28557698/48748278-440efe80-ecb1-11e8-94c6-36c1ce1fe1f5.png)
![image](https://user-images.githubusercontent.com/28557698/48748283-4cffd000-ecb1-11e8-8329-9f4b409fecaf.png)

**Comment by farminf** [comment]
@MrSandManSy Thanks for explanation. I got the point and yes that is the issue. I need to refactor some code on the component update since - not only the states that are not related to pannellum component - ,but also by updating some of the pannellum props it shouldn't re-render the whole component.
In next days I fix it and release new version. Thanks again for pointing out this issue

**Comment by MrSandManSy** [comment]
@farminf Ok,Thanks for reply in time.Your are welcome.

**Comment by farminf** [comment]
I'm closing this and opened #35 for the issue
