### ISSUE TITLE
How to custom the 'Hotspot' icon

### ISSUE THREAD

**Issue by MrSandManSy** [farminf/pannellum-react#33]
<Pannellum.Hotspot
            type="custom"
            pitch={0}
            yaw={150}
            handleClick={(evt, args) => this.changeImg()}
          />

![image](https://user-images.githubusercontent.com/28557698/48757085-8565d500-ecd6-11e8-9ae9-c86cb80a1096.png)

In full view nagivation, the arrow icon seems to be better.
Is there any way to custom the icon?

![image](https://user-images.githubusercontent.com/28557698/48757269-1f2d8200-ecd7-11e8-955c-37d467e7d253.png)

**Comment by MrSandManSy** [comment]
@farminf Thanks for reply.I'll try it tomorrow.

**Comment by farminf** [comment]
Yes you can have it as important in your css.
```
div.pnlm-tooltip span {
  visibility: visible !important;
}
```
or you can make a custom hotspot and write your css class and pass it as a prop.

anyway, maybe would be a good idea to have it as a prop for hotspot!

**Comment by MrSandManSy** [comment]
@farminf Ah,good idea.

**Comment by MrSandManSy** [comment]
@farminf It seems like not support local image source.
```
  hotspotTooltip = (hotSpotDiv, args) => {
    const imageDiv = document.createElement('img');
    imageDiv.setAttribute('width', '45');
    imageDiv.setAttribute('height', '45');
    imageDiv.setAttribute('src', '../../../assets/images/arrow-up.jpg') // https://img.icons8.com/ios/1600/circled-up-filled.png
    hotSpotDiv.appendChild(imageDiv);
    console.log(hotSpotDiv)
  }
```
![image](https://user-images.githubusercontent.com/28557698/48832703-b87e9600-edb4-11e8-821d-db79b7434ad1.png)

**Comment by farminf** [comment]
check you path, make it in the way that you address it from root of your project.
This is my example with your image which is working
![screen shot 2018-11-21 at 21 13 38](https://user-images.githubusercontent.com/4580370/48866318-b88d8e80-edd2-11e8-8613-3328d7b0886e.png)

**Comment by martinodonnell** [comment]
@farminf/@MrS   Could you write a full component for this? I can not work out how to get a custom image on the panorama.

Also I don't know if this is possible but could a transparent poly image be added to mask a certain object in the image.Then the user could select this causing the handleClick event to trigger. For example, there is a newspaper in the picture. When the user clicks on it, a modal will appear with the text of the paper.

**Comment by farminf** [comment]
what do you mean a full component? 
you should have the image in your project folder with the correct path.
and yes it is possible. just need to give the yaw and pitch of that object to the Hubspot so it mask it.
