### ISSUE TITLE
changing any state in the component, makes re-render the image

### ISSUE THREAD

**Issue by farminf** [farminf/pannellum-react#35]
![image](https://user-images.githubusercontent.com/28557698/48681158-b01f3300-ebdb-11e8-89ba-f710958ff934.png)

_Originally posted by @MrSandManSy in https://github.com/farminf/pannellum-react/issues/28#issuecomment-439744504_

**Comment by farminf** [comment]
@MrSandManSy  yeah this can be the simple solution for solving your case but the problem is then if you change(update) only yaw or pitch or whatever props of component, the component wouldn't update the component.
I was looking for a better solution to cover all updates

**Comment by MrSandManSy** [comment]
@farminf Well done!

**Comment by farminf** [comment]
Try the latest version (new release 1.1.1) and the issue should be fixed :)
