### ISSUE TITLE
'npm run build' success,but missing some file

### ISSUE THREAD

**Issue by MrSandManSy** [farminf/pannellum-react#36]
![image](https://user-images.githubusercontent.com/28557698/48879558-3d19f480-ee47-11e8-9345-e9cb52edb9c7.png)

![image](https://user-images.githubusercontent.com/28557698/48885195-58dec400-ee62-11e8-9645-022ded66fc06.png)

Missing css and index.html.

This is your's.
![image](https://user-images.githubusercontent.com/28557698/48885160-38af0500-ee62-11e8-8f4a-bb5e34f35928.png)

**Comment by MrSandManSy** [comment]
I'm sorry.I just see 'htmlWebpackPlugin'.The css and html generated in this place.
![image](https://user-images.githubusercontent.com/28557698/48885454-5df04300-ee63-11e8-8463-064b80bf98e9.png)

**Comment by MrSandManSy** [comment]
I'm sorry.I was stupid.I just see 'html-webpack-plugin'.All missing css and html are in 'src/pannellum/css'.

**Comment by farminf** [comment]
No prob...  try `npm run build --  --copy-files` for building it with css files included

**Comment by MrSandManSy** [comment]
@farminf Thanks.I get it.

**Comment by shawnphoffman** [comment]
FWIW: I noticed this issue as well when I try to import the package via yarn. Yarn add doesn't include the missing files so I'll have to include the package manually.
