### ISSUE TITLE
Got a VideoJS warning in console

### ISSUE THREAD

**Issue by LitoMore** [farminf/pannellum-react#44]
Seems we are using a deprecated API of the VideoJS.

I got this warning in the console.

```
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
```

**Comment by w3code** [comment]
Same here.

**Comment by LitoMore** [comment]
fixes #45

**Comment by w3code** [comment]
@LitoMore Ok, thanks.

**Comment by farminf** [comment]
@LitoMore try install with next tag
`npm install pannellum-react@next`
