### ISSUE TITLE
Viewer Jumping with custom minYaw maxYaw 

### ISSUE THREAD

**Issue by rafael-fuzitani** [farminf/pannellum-react#48]
Hi,

I'm facing a issue when setting up minYaw and maxYaw.
The problem happens when the viewer reaches the maxYaw value. My intention is to lock the viewer to not pass further than the maxYaw, but sometimes the view jumps from the max to the min value.

It is not too bad if the first yaw is set to 0 because the limits can stay far away from the 180 and -180, as you can see in the GIF below it takes some effort to make it happen. 

The Code:
```
   yaw: 0,
    minYaw: -140,
    maxYaw: 140,
```
The Result:
![5c1a9137111f6051506024](https://user-images.githubusercontent.com/20917194/50240903-3da59c80-03ad-11e9-85e9-ae729d96e78b.gif)

However if I set one of the values close to 180 or -180, it becomes really sensitive and jumps right away.

The Code:
```
          yaw: 0,
          minYaw: -140,
          maxYaw: 180,
```

The Result:
![webp net-resizeimage](https://user-images.githubusercontent.com/20917194/50245513-d5a98300-03b9-11e9-948f-285bcdea333b.gif)

I'm setting those values via state of the component. Because the user can select different images, so each yaw, and min/max yaw values are taken from these states. I have a bunch of states like this one below.

```
   bolhaPetPlace: {
          img: bolhaPetPlace,
          foto: fotoPetPlace,
          pitch: 0,
          minPitch: -70,
          maxPitch: 80,

          yaw: 0,
          minYaw: -140,
          maxYaw: 140,

          hfov: 100,
          maxHfov: 110,
          minHfov: 100,
          hotSpotNumbers: 0,
          hotSpots: [
            {
              pitch: 0,
              yaw: 0,
              tooltipText: "Pet Place",
              handleClickArg: "PetPlace"
            }
          ]
        },
```

And I'm selecting witch one accordingly to another state set on another component 

```
let witchBolha = this.props.currentBolha;

switch (witchBolha) {

    case "pet-place":
    selectedBolhaData = this.state.bolhasData.bolhaPetPlace;
    break;
    
    /* other cases*/

}
```

And then picking each value from it

```
    selectedBolha = selectedBolhaData.img;
    selectedFoto = selectedBolhaData.foto;
    pitch = selectedBolhaData.pitch;
    minPitch = selectedBolhaData.minPitch;
    maxPitch = selectedBolhaData.maxPitch;
    yaw = selectedBolhaData.yaw;
    minYaw = selectedBolhaData.minYaw;
    maxYaw = selectedBolhaData.maxYaw;
    hfov = selectedBolhaData.hfov;
    minHfov = selectedBolhaData.minHfov;
    maxHfov = selectedBolhaData.maxHfov;
```

Finally inserting everything into <Pannellum />

```
<Pannellum
          width="100%"
          height="100%"
          image={selectedBolha}
          pitch={pitch}
          minPitch={minPitch}
          maxPitch={maxPitch}
          yaw={yaw}
          minYaw={minYaw}
          maxYaw={maxYaw}
          hfov={hfov}
          minHfov={minHfov}
          maxHfov={maxHfov}
          showControls={true}
          autoLoad
          autoRotate={0}
          onLoad={() => {
            document
              .querySelector(".pnlm-render-container")
              .classList.add("fadeIn");
          }}
        >
          {this.createHotspots(selectedBolhaData)}
        </Pannellum>
```

I'm sorry if I was confusing or my code is messy.
I'm a beginner in programming and even new to React.

Is there any way to work around this? 

Thanks!

**Comment by farminf** [comment]
@rafael-fuzitani Thanks you for opening this and the code is clear :)
I checked it and I noticed that it is actually because of the drag event. It happens when you do the long drag on the viewer and it calculates the drag and arrives at -140 or whatever value. In fact, it is going to be easier when you set it close to 180 because it takes a shorter drag to arrive at -140.
I checked the Pannellum itself and it seems that it has the same issue. I try to search in the Pannellum library to understand if there would be a workaround from my part. If not we need to open an issue on Pannellum repo.

**Comment by rafael-fuzitani** [comment]
@farminf Thanks for the quick reply. 

Didn't know about this calculation it does. 
Having that im mind I'll try to look for something here as well.

> I checked the Pannellum itself and it seems that it has the same issue. I try to search in the Pannellum library to understand if there would be a workaround from my part. If not we need to open an issue on Pannellum repo.

Ok!

**Comment by farminf** [comment]
check this out https://github.com/mpetroff/pannellum/issues/698
