### ISSUE TITLE
How to access video controlls?

### ISSUE THREAD

**Issue by robin22d** [farminf/pannellum-react#49]
How call the functions of the video like play, pause and current time?

Thanks

**Comment by farminf** [comment]
By having react "ref" on the component and then "this.ref.current.video" gives you the video js parameters like pause() or play().

```js
// in constructor
this.ref = React.createRef();
// in render
<PannellumVideo
                ref={this.ref}

```

instead, if you want pannellum viewer then by getViewer() on ref.
