### ISSUE TITLE
not able to drag image from imiddle 

### ISSUE THREAD

**Issue by gmchaturvedi1** [farminf/pannellum-react#53]
i am using the following code  but not able to drag image from middle and only small top left is draggable :  

   <Pannellum
                                width="100%"
                                height="400px"
                                image={ArmImg}
                                pitch={10}
                                yaw={180}
                                hfov={500}
                                autoLoad
                                author=""
                                title=""
                                orientationOnByDefault={false}
                                draggable
                                keyboardZoom
                                mouseZoom
                                preview=""
                                previewAuthor=""
                                previewTitle=""
                                showControls
                                showFullscreenCtrl
                                showZoomCtrl
                                onLoad={() => {
                                    console.log("panorama loaded");
                                }}
                            >
                                <Pannellum.Hotspot
                                    type="info"
                                    pitch={11}
                                    yaw={-167}
                                    text="Info Hotspot Text 3"
                                    URL="https://github.com/farminf/pannellum-react"
                                />

                                <Pannellum.Hotspot
                                    type="info"
                                    pitch={31}
                                    yaw={-107}
                                    text="Info Hotspot Text 4"
                                    URL="https://github.com/farminf/pannellum-react"
                                />
                            </Pannellum>

kindly guide if i am doing something wrong.

thanks & Reagrds
gmchaturvedi

**Comment by farminf** [comment]
I'm not sure if draging was part of the features
