### ISSUE TITLE
Package Size Improvements

### ISSUE THREAD

**Issue by dhantke** [farminf/pannellum-react#60]
When using the _pannellum-react_ component via `import {Pannellum} from "pannellum-react"` as suggested, the whole _video.js_ library will be imported/bundled with the project build.

By using `import Pannellum from "pannellum-react/es/elements/Pannellum"` the _video.js_ component will be skipped, which decreases the production build by more than 500kb.

This is not really a bug, but it should be documented.

**Comment by farminf** [comment]
Thanks, I'll add it to readme, you can also open a PR for this if you like
