### ISSUE TITLE
componentDidUpate version 1.2.2

### ISSUE THREAD

**Issue by maciekpastuszka** [farminf/pannellum-react#61]
Package installed by npm is different than repo. (version 1.2.2)

I noticed that in `es/elements/Pannellum.js` method `componentDidUpdate` had only `this.renderImage("update")` without any conditions, which are existing in 1.1.3.

**Comment by farminf** [comment]
@maciekpastuszka thanks... I think I had publish the package from another pc which had old build files
check 1.2.3 please
