### ISSUE TITLE
I cannot build my app. Missing files

### ISSUE THREAD

**Issue by cabralada** [farminf/pannellum-react#63]
Hi. I did install. All good. 
but I just added the code to run the plugin and I have this error:

```
ERROR in ./node_modules/pannellum-react/lib/elements/Pannellum.js
Module not found: Error: Can't resolve '../pannellum/css/pannellum.css'

ERROR in ./node_modules/pannellum-react/lib/elements/PannellumVideo.js
Module not found: Error: Can't resolve '../pannellum/css/pannellum.css'
```

Im running your this code: 

```
<Pannellum
	width="100%"
	height="500px"
	image={`./assets/img/placeholder/360image.jpg`}
	pitch={10}
	yaw={180}
	hfov={110}
	autoLoad
	onLoad={loaded360}
/>
```

some missing peace that I doing wrong?

**Comment by lucifercuns** [comment]
I have the same problem too :(

**Comment by aghoneim92** [comment]
Same here

**Comment by yangtheng2359** [comment]
same here

**Comment by sanderdewijs** [comment]
It looks like the entire css folder is missing from the npm package in the /pannellum directory

**Comment by sanderdewijs** [comment]
For my project, switching back to version 1.1.3 fixed the issue.

**Comment by cabralada** [comment]
@sanderdewijs I did also use Storybook in your project?
did you had some issue?

because my storybook dosent work ... with this version 1.1.3

=(

Looks like that this tool has too many bugs

**Comment by sanderdewijs** [comment]
No sorry I did not use Storybook. Perhaps you could manually add the css directory in the node_modules as a workaround?

**Comment by minsikim** [comment]
@cabralada Thanks this fixed my problem too. running in `"react": "^16.8.6",`

**Comment by jstorm31** [comment]
#62 should fix it when merged

**Comment by farminf** [comment]
please try again... Thansk for the PR @jstorm31 
sorry for the delay everyone

**Comment by jstorm31** [comment]
Version `1.2.4` fixed this for me. I think the issue can be closed now.
