### ISSUE TITLE
orientationOnByDefault doesn't work

### ISSUE THREAD

**Issue by swapnildubal** [farminf/pannellum-react#64]
Hello, 
How do you add the gyrosensor to it? I have added the orientationOnByDefault prop, but it's not working.

Below is the code:

`<Pannellum
        width="100%"
        image={myImage}
        pitch={10}
        hfov={110}
        vaov={90}
        vOffset={1}
        yaw={180}
        maxHfov={170}
        minHfov={30}
        autoLoad
        showZoomCtrl={false}
        showFullscreenCtrl={false}
        orientationOnByDefault
      >
      </Pannellum>`

Package versions:

    "pannellum-react": "1.1.3",
     "react": "^16.8.6",

**Comment by farminf** [comment]
hi, which device and which component? (image or video)

**Comment by swapnildubal** [comment]
The issue was with http, gyrosensor works only on https.
Thanks
