### ISSUE TITLE
Custom Controls.

### ISSUE THREAD

**Issue by ED1Yang** [farminf/pannellum-react#71]
Hello farminf,
Thank you for putting pannellum into react, really helped me a lot.
Recently I've been working on a project which required to have a map over the 360 photo.
It's similar to a custom controls. (https://pannellum.org/documentation/examples/custom-controls/), the difference is just to put a image on the button, rather than a simple icon.

Is it possible in the pannellum-react? Thank you very much.

**Comment by farminf** [comment]
Hi, welcome, happy to hear that.
yeah, you can!  you just create your image buttons and by doing some CSS works (in the example there are) put it on top of pannellum div and then as an onClick of the buttons you change the yaw, pitch and etc with the callbacks which are provided by the component.

**Comment by ED1Yang** [comment]
> Hi, welcome, happy to hear that.
> yeah, you can! you just create your image buttons and by doing some CSS works (in the example there are) put it on top of pannellum div and then as an onClick of the buttons you change the yaw, pitch and etc with the callbacks which are provided by the component.

Thank you farminf.
Yes in the example there are possible solutions from the pure JS perspective.
But is it possible to realize this feature by React?
Here are some questions that I'm not sure at the moment.

1. I'm trying to add control buttons inside the `<Pannellum> </Pannellum>` but it didn't work.
2. Is there any possible way to add a control button via someway like this?
`<Pannellum.Controls
            type="button"
            position={top: 20px, left :20px}
            handleClick={(evt, args) => console.log(args.name)}
/>`
3. I can create a button and make it appears on the 360 photo manually by CSS. But when we play it by fullscreen, all the customized buttons will disappear.

Thank you very much.
