### ISSUE TITLE
Can't create hotspots dynamically

### ISSUE THREAD

**Issue by danydhondt** [farminf/pannellum-react#74]
If I want to create several hotspots dynamically, I get a javascript error.

Code to generate the error:
This will work:

    <Pannellum ...>
        <Pannellum.Hotspot type='custom'/>
    </Panellum>

But this will not:

    <Pannellum ...>
        {[1, 2, 3].map(i => <Pannellum.Hotspot key={i} type='custom'/>)}
    </Panellum>

The error that is generated is very weird:

![image](https://user-images.githubusercontent.com/34274779/69010182-6d627900-095d-11ea-8304-deab558cb925.png)

Debugging inside this function shows that `hotspots` is indeed an array of objects containing a property `props`. But once inside the `map` function, `hotspot` is an array identical to `hotspots`

I'll try to create a codepen and come back with that.
Maybe you'll know the error already?

thx

**Comment by danydhondt** [comment]
Managed to solve it myself:

You can't **mix** dynamically created children with hardcoded children.

So, this **will** work:

    <Pannellum ...>
        {[1, 2, 3].map(i => <Pannellum.Hotspot key={i} type='custom'/>)}
    </Panellum>

But this **won't**:

    <Pannellum ...>
        {[1, 2, 3].map(i => <Pannellum.Hotspot key={i} type='custom'/>)}
        <Pannellum.Hotspot type='custom'/>
    </Panellum>

**Comment by farminf** [comment]
You can make your mix array before render, then pass it to Pannellum component.
