### ISSUE TITLE
UI Icons are invisible

### ISSUE THREAD

**Issue by torokze** [farminf/pannellum-react#76]
Hi,

Is there something I forgot to set? All the navigation icons are missing.

![image](https://user-images.githubusercontent.com/4497372/70704937-50f2fb80-1cd3-11ea-9e8f-b6a0f8a4f966.png)

**Comment by farminf** [comment]
Hi,

check if you have _sprite.svg_ file in this path `node_modules/pannellum-react/lib/pannellum/css/img`.
if not, try to install the lib again

**Comment by torokze** [comment]
It's already there.

**Comment by torokze** [comment]
The image-webpack-loader solved the case.
