### ISSUE TITLE
Can't able to stop autoplay in pannelleum video.

### ISSUE THREAD

**Issue by Maruthasalam** [farminf/pannellum-react#79]
I can't able stop the video in the intial page loading.i have set auto play false but still not working
auto play is not working here is my code
<PannellumVideo
        autoPlay ={false}
        video="/360_videos/file.mp4"
        width="100%"
        height="216px"
        controls = {true}
      >
      </PannellumVideo>
https://codesandbox.io/s/aged-waterfall-klwxw
Please any oe help me to fix this one?

**Comment by farminf** [comment]
Hey, 
sorry for the late reply... can you provide a link or you code here? cause that link is an image

**Comment by Maruthasalam** [comment]
yea sure.
Here is my code..
I have given auto play false but by default it is true.i have tried to stop auto play when it in initial loading.
      <PannellumVideo
          video="/360Videos/smaple.mp4"
          autoplay={false}
          muted={false}
          width="100%"
          height="216px"
          controls={true} 
        ></PannellumVideo>

**Comment by Maruthasalam** [comment]
<PannellumVideo
          ref={video_ref}
          video={media_urls[0]}
          muted={false}
          width="100%"
          height="216px"
          controls={true}
          draggable ={true}
        ></PannellumVideo>

**Comment by farminf** [comment]
so sorry for the late reply, if this is still an issue please reopen this issue and I take a look!
