### ISSUE TITLE
Honour style property

### ISSUE THREAD

**Issue by torokze** [farminf/pannellum-react#81]
Hi, 

<Pannellum width="100%" height="100%" style={...} ... />

Should honour other styling not just width/height.

Zolee

**Comment by farminf** [comment]
These are pannellum (the main library) props not the CSS styles.

**Comment by torokze** [comment]
Yes, i know but when I try to use 'style' it is not applied on the DOM node of the pannellum.

**Comment by torokze** [comment]
How can I add more styling to this?
<Panelllum style={{ ... }} /> doesn't work obviously.

`render() {
    let { width, height } = this.props;
    **let divStyle = {
      width: width,
      height: height
    };**
    return (
      <div
        id={this.props.id ? this.props.id : this.state.id}
        **style={divStyle}**
        ref={node => (this.imageNode = node)}
      />
    );
  }`
