### ISSUE TITLE
Controls are blank but working

### ISSUE THREAD

**Issue by leevimatias** [farminf/pannellum-react#82]
The buttons show up, but the action indicator icons are missing. They are just white squares.
Is there something I'm missing with the controls? Is there a straight forward way of customizing them, i.e making my own button components?

```
 <Pannellum
      width={elementWidth}
      height={elementHeight}
      image={image}
      pitch={pitch}
      yaw={yaw}
      hfov={hfov}
      autoLoad
      onLoad={onLoadFc}
   />
```

EDIT
I seem to have found the issue, but i'm still lost like a boy in a foreign country.
There seems to be a problem loading the icon. 
```
pnlm-sprite {
    background-image: url([object Object]);
}
```

Another question that I have is if there is a way of customizing the loading indicator?

**Comment by farminf** [comment]
So sorry for replying late, if this is still your issue/question please reopen this issue
