### ISSUE TITLE
createTooltipFunc && createTooltipArgs

### ISSUE THREAD

**Issue by redbaron76** [farminf/pannellum-react#9]
Do you think it's possible to fix / correctly implement those two props?
At the moment there's an undocumented `Tooltip` prop that would play the role of `createTooltipFunc` but, not having `createTooltipArgs` implemented, it's partly useless.

Furthermore, would be great to maintain the `text` prop in custom HotSpot too, so you still can give basic tooltip functionality for those who don't need to change the tooltips behaviour.

Great job till now, anyway! That's what I was looking for...

**Comment by farminf** [comment]
Thanks :)
I implemented those props like as pannellum ones and are available in 0.2.2 (see readme)
About text: actually I want to integrate [marzipano](http://www.marzipano.net) hotspot shapes (only ui) and have different hotspot types in addition to custom and info ones.
