### ISSUE TITLE
Unable to use with React 17

### ISSUE THREAD

**Issue by TanvirMahin24** [farminf/pannellum-react#90]
While installing the package error shows up. The error:
    
    npm ERR! Found: react@17.0.2
    npm ERR! node_modules/react
    npm ERR!   react@"^17.0.2" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer react@"16.x" from pannellum-react@1.2.4
    npm ERR! node_modules/pannellum-react
    npm ERR!   pannellum-react@"1.2.4" from the root project
    

I am using React 17.0.2.

**Comment by farminf** [comment]
it should work but anyways, try new version [1.3.3](https://www.npmjs.com/package/pannellum-react/v/1.3.3) please and let me know.
the demo app in the repo works with React 17 and now it is upgraded

**Comment by kayvaninvemo** [comment]
I tried and it is still give error, I could use `npm i pannellum-react@1.3.3 --force`
